### about instance
GET http://127.0.0.1:8080/about

### update instance
POST http://localhost:8080/about/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "test2333",
  "description": "test123"
}



### get token
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

> {%
client.global.set("access_token", response.body.accessToken);
client.global.set("refresh_token", response.body.refreshToken);
%}


### about current user
GET http://localhost:8080/user/me
Authorization: Bearer {{access_token}}


### get all users
GET http://localhost:8080/user/all
Authorization: Bearer {{access_token}}


### create newuser
POST http://localhost:8080/user/create
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "user3",
  "password": "password",
  "admin": false,
  "active": false
}



### refresh token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
client.global.set("access_token", response.body.accessToken);
client.global.set("refresh_token", response.body.refreshToken);
%}


### get all tokens
GET http://localhost:8080/auth/refresh
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {% client.global.set("tokenId", response.body[0].id); %}


### delete token
POST http://localhost:8080/auth/refresh/delete
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{tokenId}}"
}


### cleanup tokens
GET http://localhost:8080/auth/refresh/cleanup
Authorization: Bearer {{access_token}}
Content-Type: application/json


### logout
GET http://localhost:8080/auth/logout
Authorization: Bearer {{access_token}}
Content-Type: application/json



### get manga list
GET http://localhost:8080/content/manga
Authorization: Bearer {{access_token}}

> {% client.global.set("title", response.body[0].id); %}


### get manga list with filter
POST http://localhost:8080/content/manga
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "offset": 0,
  "limit": 2,
  "search": null
}

> {% client.global.set("title", response.body[0].id); %}


### get current manga
GET http://localhost:8080/content/manga/{{title}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.global.set("title", response.body.id);
    client.global.set("volume", response.body.content[0].id);
    client.global.set("page", response.body.content[0].content[0].id);
%}


### update manga
POST http://localhost:8080/content/manga/{{title}}/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test123"
}


### update manga volume
POST http://localhost:8080/content/manga/{{title}}/{{volume}}/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "volume name test"
}


### get page
GET http://localhost:8080/content/manga/{{title}}/{{volume}}/{{page}}
Authorization: Bearer {{access_token}}


### get thumb
GET http://localhost:8080/content/thumb/{{title}}/{{volume}}/{{page}}
Authorization: Bearer {{access_token}}



### get all last points
GET http://localhost:8080/content/manga/last_point
Authorization: Bearer {{access_token}}


### get specific last points
GET http://localhost:8080/content/manga/{{title}}/last_point
Authorization: Bearer {{access_token}}


### set last points
POST http://localhost:8080/content/manga/{{title}}/{{volume}}/{{page}}/last_point
Authorization: Bearer {{access_token}}
