### about instance
GET http://127.0.0.1:8080/about


### get token
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

> {%
client.global.set("access_token", response.body.accessToken);
client.global.set("refresh_token", response.body.refreshToken);
%}


### test token
GET http://localhost:8080/users/me
Authorization: Bearer {{access_token}}


### refresh token
POST http://localhost:8080/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
client.global.set("access_token", response.body.accessToken);
client.global.set("refresh_token", response.body.refreshToken);
%}

### get list
GET http://localhost:8080/manga
Authorization: Bearer {{access_token}}

> {% client.global.set("title", response.body[0].id); %}

### get list POST
POST http://localhost:8080/manga
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "offset": 0,
  "limit": 2,
  "search": null
}

> {% client.global.set("title", response.body[0].id); %}

### get current manga
POST http://localhost:8080/manga/id
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "id": "{{title}}"
}

> {%
    client.global.set("title", response.body.id);
    client.global.set("volume", response.body.content[0].id);
%}

### update instance
POST http://localhost:8080/about/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "instanceName": "test2",
  "instanceDescription": "test123"
}


### update manga
POST http://localhost:8080/manga/{{title}}/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test123",
  "cover": ""
}

### update manga volume
POST http://localhost:8080/manga/{{title}}/{{volume}}/update
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "volume name test"
}


### get page
GET http://localhost:8080/manga/{{title}}/0/0
Authorization: Bearer {{access_token}}


### get thumb
GET http://localhost:8080/thumb/{{title}}/0/0
Authorization: Bearer {{access_token}}


### test newuser
POST http://localhost:8080/users/create
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "user2",
  "password": "password",
  "admin": false
}
